apiVersion: v1
kind: Service
metadata:
  name: {{ include "confidential-router-ui.fullname" . }}
  labels:
    {{- include "confidential-router-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "confidential-router-ui.selectorLabels" . | nindent 4 }}
