{{- if and .Values.masterKey (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "confidential-router-litellm.fullname" . }}
  labels:
    {{- include "confidential-router-litellm.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-key: {{ .Values.masterKey | quote }}
{{- end }}
