{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "patroni-postgresql.fullname" . }}
  labels:
    {{- include "patroni-postgresql.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "patroni-postgresql.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "patroni-postgresql.serviceAccountName" . }}
{{- end }}
